import DoDo from "./DoDo.js"
import Fox from "./Fox.js"
import Ibis from "./Ibis.js"
import Jaguar from "./Jaguar.js"
import KillerWhale from "./KillerWhale.js"
import Lemming from "./Lemming.js"
import Narwhal from "./Narwhal.js"
import Orca from "./Orca.js"
import Puffin from "./Puffin.js"
import Quokka from "./Quokka.js"
import Raccoon from "./Raccoon.js"
import Salamander from "./Salamander.js"
import TazmanianDevil from "./Tazmanian Devil.js"
import Urchin from "./Urchin.js"
import Vulture from "./Vulture.js"
import Walrus from "./Walrus.js"
import NoX from "./X-none.js"
import Yak from "./Yak.js"
import Zebra from "./Zebra.js"
import Adelie from "./Adelie.js"
import Blackfooted from "./Blackfooted.js"
import Chinstrap from "./Chinstrap.js"
import Emperor from "./Emperor.js"
import Galapagos from "./Galapagos.js"
import Humboldt from "./Humboldt.js"
import Macaroni from "./Macaroni.js"

